// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shop.Infrastructure;

#nullable disable

namespace Shop.Infrastructure.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20251020174430_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shop.Infrastructure.Entities.AdCampaigns.AdCampaignEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(102);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnOrder(103);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnOrder(100);

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(101);

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.HasKey("Id");

                    b.ToTable("AdCampaign", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.AdCampaigns.AdCampaignItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<Guid>("AdCampaignId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(101);

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(103);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("AdCampaignId", "Position", "Lang")
                        .IsUnique();

                    b.ToTable("AdCampaignItem", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.AdCampaigns.AdCampaignProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<Guid>("AdCampaignId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(101);

                    b.HasKey("Id");

                    b.HasIndex("AdCampaignId");

                    b.HasIndex("ProductId");

                    b.ToTable("AdCampaignProduct", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Baskets.BasketEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Basket", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Baskets.BasketItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<Guid>("BasketId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(101);

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("BasketId", "ProductId")
                        .IsUnique();

                    b.ToTable("BasketItem", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Categories.CategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnOrder(102);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnOrder(101);

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Categories.CategoryTranslationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnOrder(50);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(51);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Lang")
                        .IsUnique();

                    b.ToTable("CategoryTranslation", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.ProductBases.ProductBaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnOrder(101);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductBase", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.ProductBases.ProductParameterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnOrder(101);

                    b.Property<Guid>("ProductBaseId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.HasKey("Id");

                    b.HasIndex("ProductBaseId");

                    b.ToTable("ProductParameter", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.ProductBases.ProductParameterTranslationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnOrder(50);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ProductParameterId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(51);

                    b.HasKey("Id");

                    b.HasIndex("ProductParameterId", "Lang")
                        .IsUnique();

                    b.ToTable("ProductParameterTranslation", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Products.PriceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("End")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnOrder(101);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.Property<DateTime?>("Start")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(102);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Price", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Products.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnOrder(102);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnOrder(101);

                    b.Property<Guid>("ProductBaseId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.Property<bool>("WasActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ProductBaseId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Products.ProductParameterValueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.Property<Guid>("ProductParameterId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(101);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnOrder(102);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductParameterId");

                    b.ToTable("ProductParameterValue", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Products.ProductPhotoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(3);

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("ProductId", "Position")
                        .IsUnique();

                    b.ToTable("ProductPhoto", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Products.ProductTranslationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnOrder(50);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(51);

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Lang")
                        .IsUnique();

                    b.ToTable("ProductTranslation", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Promotions.PromotionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<Guid?>("AdCampaignId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnOrder(103);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnOrder(101);

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(104);

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<JsonDocument>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnOrder(107);

                    b.HasKey("Id");

                    b.HasIndex("AdCampaignId")
                        .IsUnique();

                    b.ToTable("Promotion", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Promotions.PromotionProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(101);

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PromotionId");

                    b.ToTable("PromotionProduct", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.PurchaseLists.PurchaseListEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("boolean")
                        .HasColumnOrder(102);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnOrder(101);

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.HasKey("Id");

                    b.ToTable("PurchaseList", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.PurchaseLists.PurchaseListItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(101);

                    b.Property<Guid>("PurchaseListId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseListId");

                    b.ToTable("PurchaseListItem", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.AdCampaigns.AdCampaignItemEntity", b =>
                {
                    b.HasOne("Shop.Infrastructure.Entities.AdCampaigns.AdCampaignEntity", "AdCampaign")
                        .WithMany("AdCampaignItems")
                        .HasForeignKey("AdCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdCampaign");
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.AdCampaigns.AdCampaignProductEntity", b =>
                {
                    b.HasOne("Shop.Infrastructure.Entities.AdCampaigns.AdCampaignEntity", "AdCampaign")
                        .WithMany("AdCampaignProducts")
                        .HasForeignKey("AdCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Infrastructure.Entities.Products.ProductEntity", "Product")
                        .WithMany("AdCampaignProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdCampaign");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Baskets.BasketItemEntity", b =>
                {
                    b.HasOne("Shop.Infrastructure.Entities.Baskets.BasketEntity", "Basket")
                        .WithMany("BasketItems")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Infrastructure.Entities.Products.ProductEntity", "Product")
                        .WithMany("BasketItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Categories.CategoryEntity", b =>
                {
                    b.HasOne("Shop.Infrastructure.Entities.Categories.CategoryEntity", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Categories.CategoryTranslationEntity", b =>
                {
                    b.HasOne("Shop.Infrastructure.Entities.Categories.CategoryEntity", "Category")
                        .WithMany("Translations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.ProductBases.ProductBaseEntity", b =>
                {
                    b.HasOne("Shop.Infrastructure.Entities.Categories.CategoryEntity", "Category")
                        .WithMany("ProductBases")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.ProductBases.ProductParameterEntity", b =>
                {
                    b.HasOne("Shop.Infrastructure.Entities.ProductBases.ProductBaseEntity", "ProductBase")
                        .WithMany("ProductParameters")
                        .HasForeignKey("ProductBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductBase");
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.ProductBases.ProductParameterTranslationEntity", b =>
                {
                    b.HasOne("Shop.Infrastructure.Entities.ProductBases.ProductParameterEntity", "ProductParameter")
                        .WithMany("Translations")
                        .HasForeignKey("ProductParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductParameter");
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Products.PriceEntity", b =>
                {
                    b.HasOne("Shop.Infrastructure.Entities.Products.ProductEntity", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Products.ProductEntity", b =>
                {
                    b.HasOne("Shop.Infrastructure.Entities.ProductBases.ProductBaseEntity", "ProductBase")
                        .WithMany("Products")
                        .HasForeignKey("ProductBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductBase");
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Products.ProductParameterValueEntity", b =>
                {
                    b.HasOne("Shop.Infrastructure.Entities.Products.ProductEntity", "Product")
                        .WithMany("ProductParameterValues")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Infrastructure.Entities.ProductBases.ProductParameterEntity", "ProductParameter")
                        .WithMany("ProductParameterValues")
                        .HasForeignKey("ProductParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductParameter");
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Products.ProductPhotoEntity", b =>
                {
                    b.HasOne("Shop.Infrastructure.Entities.Products.ProductEntity", "Product")
                        .WithMany("ProductPhotos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Products.ProductTranslationEntity", b =>
                {
                    b.HasOne("Shop.Infrastructure.Entities.Products.ProductEntity", "Product")
                        .WithMany("Translations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Promotions.PromotionEntity", b =>
                {
                    b.HasOne("Shop.Infrastructure.Entities.AdCampaigns.AdCampaignEntity", "AdCampaign")
                        .WithOne("Promotion")
                        .HasForeignKey("Shop.Infrastructure.Entities.Promotions.PromotionEntity", "AdCampaignId");

                    b.Navigation("AdCampaign");
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Promotions.PromotionProductEntity", b =>
                {
                    b.HasOne("Shop.Infrastructure.Entities.Products.ProductEntity", "Product")
                        .WithMany("PromotionProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Infrastructure.Entities.Promotions.PromotionEntity", "Promotion")
                        .WithMany("PromotionProducts")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.PurchaseLists.PurchaseListItemEntity", b =>
                {
                    b.HasOne("Shop.Infrastructure.Entities.Products.ProductEntity", "Product")
                        .WithMany("PurchaseListItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Infrastructure.Entities.PurchaseLists.PurchaseListEntity", "PurchaseList")
                        .WithMany("PurchaseListItems")
                        .HasForeignKey("PurchaseListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseList");
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.AdCampaigns.AdCampaignEntity", b =>
                {
                    b.Navigation("AdCampaignItems");

                    b.Navigation("AdCampaignProducts");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Baskets.BasketEntity", b =>
                {
                    b.Navigation("BasketItems");
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Categories.CategoryEntity", b =>
                {
                    b.Navigation("ProductBases");

                    b.Navigation("SubCategories");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.ProductBases.ProductBaseEntity", b =>
                {
                    b.Navigation("ProductParameters");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.ProductBases.ProductParameterEntity", b =>
                {
                    b.Navigation("ProductParameterValues");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Products.ProductEntity", b =>
                {
                    b.Navigation("AdCampaignProducts");

                    b.Navigation("BasketItems");

                    b.Navigation("Prices");

                    b.Navigation("ProductParameterValues");

                    b.Navigation("ProductPhotos");

                    b.Navigation("PromotionProducts");

                    b.Navigation("PurchaseListItems");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.Promotions.PromotionEntity", b =>
                {
                    b.Navigation("PromotionProducts");
                });

            modelBuilder.Entity("Shop.Infrastructure.Entities.PurchaseLists.PurchaseListEntity", b =>
                {
                    b.Navigation("PurchaseListItems");
                });
#pragma warning restore 612, 618
        }
    }
}
