// <auto-generated />
using System;
using Authorization.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Authorization.Infrastructure.Migrations
{
    [DbContext(typeof(AuthContext))]
    partial class AuthContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Authorization.Infrastructure.Entities.Permissions.AuthorizationPermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<int>("Permission")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.HasKey("Id");

                    b.HasIndex("PermissionGroupId", "Permission")
                        .IsUnique();

                    b.ToTable("AuthorizationPermission", (string)null);
                });

            modelBuilder.Entity("Authorization.Infrastructure.Entities.Permissions.ProductPermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<int>("Permission")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.HasKey("Id");

                    b.HasIndex("PermissionGroupId", "Permission")
                        .IsUnique();

                    b.ToTable("ProductPermission", (string)null);
                });

            modelBuilder.Entity("Authorization.Infrastructure.Entities.Permissions.ShopPermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<int>("Permission")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.HasKey("Id");

                    b.HasIndex("PermissionGroupId", "Permission")
                        .IsUnique();

                    b.ToTable("ShopPermission", (string)null);
                });

            modelBuilder.Entity("Authorization.Infrastructure.Entities.Permissions.WarehousePermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<int>("Permission")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.HasKey("Id");

                    b.HasIndex("PermissionGroupId", "Permission")
                        .IsUnique();

                    b.ToTable("WarehousePermission", (string)null);
                });

            modelBuilder.Entity("Authorization.Infrastructure.Entities.PrermissionGroups.PermissionGroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(100);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PermissionGroup", (string)null);
                });

            modelBuilder.Entity("Authorization.Infrastructure.Entities.Users.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnOrder(103);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnOrder(102);

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid")
                        .HasColumnOrder(101);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("Authorization.Infrastructure.Entities.Users.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnOrder(103);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnOrder(100);

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(104);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6669a68-5afb-432d-858f-3f5181579a90"),
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "superadmin@futureshop.pl",
                            FirstName = "Super",
                            HashedPassword = "$2a$11$v1B9qwcIeH.PJLuFjnmK7O1Nu3TSUsc6oZ49.5DXOJhkIDcfzPD..",
                            LastName = "Admin",
                            Type = 0
                        });
                });

            modelBuilder.Entity("Authorization.Infrastructure.Entities.Users.UserPermissionGroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(101);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(100);

                    b.HasKey("Id");

                    b.HasIndex("PermissionGroupId");

                    b.HasIndex("UserId", "PermissionGroupId")
                        .IsUnique();

                    b.ToTable("UserPermissionGroup", (string)null);
                });

            modelBuilder.Entity("Authorization.Infrastructure.Entities.Permissions.AuthorizationPermissionEntity", b =>
                {
                    b.HasOne("Authorization.Infrastructure.Entities.PrermissionGroups.PermissionGroupEntity", "PermissionGroup")
                        .WithMany("AuthorizationPermissions")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("Authorization.Infrastructure.Entities.Permissions.ProductPermissionEntity", b =>
                {
                    b.HasOne("Authorization.Infrastructure.Entities.PrermissionGroups.PermissionGroupEntity", "PermissionGroup")
                        .WithMany("ProductPermissions")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("Authorization.Infrastructure.Entities.Permissions.ShopPermissionEntity", b =>
                {
                    b.HasOne("Authorization.Infrastructure.Entities.PrermissionGroups.PermissionGroupEntity", "PermissionGroup")
                        .WithMany("ShopPermissions")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("Authorization.Infrastructure.Entities.Permissions.WarehousePermissionEntity", b =>
                {
                    b.HasOne("Authorization.Infrastructure.Entities.PrermissionGroups.PermissionGroupEntity", "PermissionGroup")
                        .WithMany("WarehousePermissions")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("Authorization.Infrastructure.Entities.Users.RefreshTokenEntity", b =>
                {
                    b.HasOne("Authorization.Infrastructure.Entities.Users.UserEntity", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("Authorization.Infrastructure.Entities.Users.RefreshTokenEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Authorization.Infrastructure.Entities.Users.UserPermissionGroupEntity", b =>
                {
                    b.HasOne("Authorization.Infrastructure.Entities.PrermissionGroups.PermissionGroupEntity", "PermissionGroup")
                        .WithMany("UserPermissionGroups")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Authorization.Infrastructure.Entities.Users.UserEntity", "User")
                        .WithMany("UserPermissionGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Authorization.Infrastructure.Entities.PrermissionGroups.PermissionGroupEntity", b =>
                {
                    b.Navigation("AuthorizationPermissions");

                    b.Navigation("ProductPermissions");

                    b.Navigation("ShopPermissions");

                    b.Navigation("UserPermissionGroups");

                    b.Navigation("WarehousePermissions");
                });

            modelBuilder.Entity("Authorization.Infrastructure.Entities.Users.UserEntity", b =>
                {
                    b.Navigation("RefreshToken");

                    b.Navigation("UserPermissionGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
